name = "CreatePack"
author = "MCGooglesss"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36307d8b3123e7de077426c4857e93c5cd04d00bf331728a1039529095a0ad48"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.79"
