name = "CreatePack"
author = "MCGooglesss"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30024e7afa584cceb7bf59adeb51ec8248c23a4f84ab2631903ec7c835c65344"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.79"
