name = "Letsplay"
author = "MCGooglesss"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e349e3300069cc89fd07a3426717fd2573bec80f56b5821035cd1228a71bf43"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
