name = "Letsplay"
author = "MCGooglesss"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "165690a3df126e52e082e01d0b59bbc6141dc925259d25cf6c958cd8daa6ef04"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
