name = "Letsplay"
author = "MCGooglesss"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd482ea8885cfe088f4c5f909e56d3c4c57f3d4da39be07fa1cb0866a9760758"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
