name = "Letsplay"
author = "MCGooglesss"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45500aacccfd5cd2979ef563578b635ab12ae23bbc04b3d132fc3d0a6ed6eccf"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
